-- PDR Manager Pro: esquema Supabase
create table if not exists public.pdr_cloud (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  data jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);
alter table public.pdr_cloud enable row level security;
drop policy if exists "pdr_cloud_select_own" on public.pdr_cloud;
drop policy if exists "pdr_cloud_insert_own" on public.pdr_cloud;
drop policy if exists "pdr_cloud_update_own" on public.pdr_cloud;
create policy "pdr_cloud_select_own" on public.pdr_cloud for select using (auth.uid() = user_id);
create policy "pdr_cloud_insert_own" on public.pdr_cloud for insert with check (auth.uid() = user_id);
create policy "pdr_cloud_update_own" on public.pdr_cloud for update using (auth.uid() = user_id);
